In [1]:
import pandas as pd
import numpy as np

file_name_6="data\\veneto.txt"
data_6=pd.read_csv(file_name_6,delimiter=';',header=0,quoting=0,error_bad_lines=False,encoding="Latin-1")
df_6=pd.DataFrame(data_6)
df_6['Origine'] = df_6['Origine'].astype(str).str[:-3]
df_6['Total_Mete'] = df_6['Total_Mete'].astype(str).str[:6]


df_6_co=df_6[(df_6['Name'] == "1272 - 28001") |
             (df_6['Name'] == "2158 - 28001") |
             (df_6['Name'] == "3106 - 28001") |
             (df_6['Name'] == "4078 - 28001") |
             (df_6['Name'] == "5005 - 28001") |
             (df_6['Name'] == "6003 - 28001") |
             (df_6['Name'] == "96004 - 28001") |
             (df_6['Name'] == "103072 - 28001") |
             (df_6['Name'] == "7003 - 28001") |
             (df_6['Name'] == "12133 - 28001") |
             (df_6['Name'] == "13075 - 28001") |
             (df_6['Name'] == "14061 - 28001") |
             (df_6['Name'] == "15146 - 28001") |
             (df_6['Name'] == "16024 - 28001") |
             (df_6['Name'] == "17029 - 28001") |
             (df_6['Name'] == "18110 - 28001") |
             (df_6['Name'] == "19036 - 28001") |
             (df_6['Name'] == "20030 - 28001") |
             (df_6['Name'] == "97042 - 28001") |
             (df_6['Name'] == "98031 - 28001") |
             (df_6['Name'] == "108033 - 28001") |
             (df_6['Name'] == "21008 - 28001") |
             (df_6['Name'] == "22205 - 28001") |
             (df_6['Name'] == "23091 - 28001") |
             (df_6['Name'] == "24116 - 28001") |
             (df_6['Name'] == "25006 - 28001") |
             (df_6['Name'] == "26086 - 28001") |
             (df_6['Name'] == "27042 - 28001") |
             (df_6['Name'] == "28060 - 28001") |
             (df_6['Name'] == "29041 - 28001") |
             (df_6['Name'] == "30129 - 28001") |
             (df_6['Name'] == "31007 - 28001") |
             (df_6['Name'] == "32006 - 28001") |
             (df_6['Name'] == "93033 - 28001") |
             (df_6['Name'] == "8031 - 28001") |
             (df_6['Name'] == "9056 - 28001") |
             (df_6['Name'] == "10025 - 28001") |
             (df_6['Name'] == "11015 - 28001") |
             (df_6['Name'] == "33032 - 28001") |
             (df_6['Name'] == "34027 - 28001") |
             (df_6['Name'] == "35033 - 28001") |
             (df_6['Name'] == "36023 - 28001") |
             (df_6['Name'] == "37006 - 28001") |
             (df_6['Name'] == "38008 - 28001") |
             (df_6['Name'] == "39014 - 28001") |
             (df_6['Name'] == "40012 - 28001") |
             (df_6['Name'] == "99014 - 28001") |
             (df_6['Name'] == "45010 - 28001") |
             (df_6['Name'] == "46017 - 28001") |
             (df_6['Name'] == "47014 - 28001") |
             (df_6['Name'] == "48017 - 28001") |
             (df_6['Name'] == "49009 - 28001") |
             (df_6['Name'] == "50026 - 28001") |
             (df_6['Name'] == "51002 - 28001") |
             (df_6['Name'] == "52032 - 28001") |
             (df_6['Name'] == "53011 - 28001") |
             (df_6['Name'] == "100005 - 28001") |
             (df_6['Name'] == "55032 - 28001") |
             (df_6['Name'] == "41044 - 28001") |
             (df_6['Name'] == "42002 - 28001") |
             (df_6['Name'] == "43023 - 28001") |
             (df_6['Name'] == "44007 - 28001") |
             (df_6['Name'] == "109006 - 28001") |
             (df_6['Name'] == "54039 - 28001") |
             (df_6['Name'] == "56059 - 28001") |
             (df_6['Name'] == "57059 - 28001") |
             (df_6['Name'] == "58091 - 28001") |
             (df_6['Name'] == "59011 - 28001") |
             (df_6['Name'] == "60038 - 28001") |
             (df_6['Name'] == "66049 - 28001") |
             (df_6['Name'] == "67041 - 28001") |
             (df_6['Name'] == "68028 - 28001") |
             (df_6['Name'] == "69022 - 28001") |
             (df_6['Name'] == "70006 - 28001") |
             (df_6['Name'] == "94023 - 28001") |
             (df_6['Name'] == "61022 - 28001") |
             (df_6['Name'] == "62008 - 28001") |
             (df_6['Name'] == "63049 - 28001") |
             (df_6['Name'] == "64008 - 28001") |
             (df_6['Name'] == "65116 - 28001") |
             (df_6['Name'] == "71024 - 28001") |
             (df_6['Name'] == "72006 - 28001") |
             (df_6['Name'] == "73027 - 28001") |
             (df_6['Name'] == "74001 - 28001") |
             (df_6['Name'] == "75035 - 28001") |
             (df_6['Name'] == "110001 - 28001") |
             (df_6['Name'] == "110002 - 28001") |
             (df_6['Name'] == "110009 - 28001") |
             (df_6['Name'] == "76063 - 28001") |
             (df_6['Name'] == "77014 - 28001") |
             (df_6['Name'] == "78045 - 28001") |
             (df_6['Name'] == "79023 - 28001") |
             (df_6['Name'] == "80063 - 28001") |
             (df_6['Name'] == "101010 - 28001") |
             (df_6['Name'] == "102047 - 28001") |
             (df_6['Name'] == "81021 - 28001") |
             (df_6['Name'] == "82053 - 28001") |
             (df_6['Name'] == "83048 - 28001") |
             (df_6['Name'] == "84001 - 28001") |
             (df_6['Name'] == "85004 - 28001") |
             (df_6['Name'] == "86009 - 28001") |
             (df_6['Name'] == "87015 - 28001") |
             (df_6['Name'] == "88009 - 28001") |
             (df_6['Name'] == "89017 - 28001") |
             (df_6['Name'] == "90064 - 28001") |
             (df_6['Name'] == "91051 - 28001") |
             (df_6['Name'] == "92009 - 28001") |
             (df_6['Name'] == "95038 - 28001") |
             (df_6['Name'] == "111009 - 28001") ]
df_6_co=df_6_co.drop(['Origine', 'Destinazione','Total_Minu'], axis=1)
df_6_co.to_csv (r'data\\distances_for_padova.csv', index = False, header=True)